
### the paths will later be given through the command line

modelpath: pilot_data/Human-GEM11.xml
expressionpath: pilot_data/gene_IDs_meanvalues.csv
output_path: pilot_data_results/

### these parameters are for the metabolic model

modelname: human1
# Currently only supports human1, recon1, recon2, iMM1865, zebrafish1

### these parameters are for the gene expression file

gene_ID_column: gene_IDs
# name of the column containing gene IDs
gene_expression_columns: DMSO, BPA
# names of the columns containing gene expression data
# column names must be separated by commas (example: condition1,condition2,condition3)
# if empty, all columns (except the gene_ID_column) will be used

gpr_parameters:
  qualitative: true
  # if true, the gene expression will be converted to reaction weights -1/0/1
  # if false, the expression will directly be mapped to the reactions
  percentile: 0.05
  # the percentile cutoff for low/high gene expression
  # example: with 0.25, the genes with the lowest 25% expression are converted to -1, and the highest 25% expression to 1


### these parameters are for the network enumeration

force_active_reactions: true
# define whether some reactions in the model should be forced to carry flux
active_reactions: # use the reaction IDs from the model to define the reactions which must carry flux
#  - MAR13082 # this is the generic biomass reaction for human1
  - MAR09931 # this is the biomass maintenance reaction with upper bound 0
fluxvalue: 1e-4
# minimum value that the flux should have.

rxn_enum_iterations: 3
div_enum_iterations: 3
# number of iterations for reaction-enum and diversity-enum (if using the main.py script)

### these parameters are for the network computation in the final step

final_network: union
# defines the method used for computing the network at the end of the workflow
# must be either 'union' or 'minimal'
# 'union' contains all reactions which are active in at least one DEXOM solution
# 'minimal' contains only the reactions which are active in every solution + the reactions necessary to make the network flux-consistent