
### the paths will later be given through the command line

modelpath: 'pilot_data/Human-GEM11.xml'
expressionpath: 'pilot_data/gene_IDs_meanvalues.csv'

### these parameters are for the model that will be used throughout the pipeline

modelname: human1

output_path: pilot_data/

### these parameters are for the gene expression file

gene_ID_column: gene_IDs
# name of the column containing gene IDs
gene_expression_columns: DMSO,BPA
# names of the columns containing gene expression data
# column names must be separated by commas (example: condition1,condition2,condition3)

gpr_parameters:
  qualitative: true
  # if true, the gene expression will be converted to reaction weights -1/0/1
  # if false, the expression will directly be mapped to the reactions
  percentile: 0.25
  # the percentile cutoff for low/high gene expression
  # with 0.25, the genes with the lowest 25% expression are converted to -1, and the highest 25% expression to 1
