
### these are the main filepaths used in the pipeline

modelpath: testdata/iJO1366.xml
# must be a valid cobrapy model (either .xml, .json, or .mat)

expressionfile: testdata/iJO1366_genedata.csv
# must be a csv file with gene identifiers in one column and gene expression data in other columns
# accepted delimiters: comma (,), semicolon (;), tab (\t)
# your gene IDs cannot contain special characters such as ; or ,

output_path: testdata_results
# path to a folder in which the output files will be saved. If the folder does not exist, it will be created


### these parameters are for the gene expression file

reaction_scores: false
# set this to true if the expressionfile already contains reaction identifiers instead of gene identifiers.
# If true, the conversion of gene expression to reaction weights will be skipped, and the provided scores will be mapped directly on the reactions.

gene_ID_column: ID
# name of the column containing gene IDs

gene_expression_columns:
# names of the columns containing gene expression data
# column names must be separated by commas (example: condition1,condition2,condition3)
# if empty, all columns (except the gene_ID_column) will be used

duplicates: remove
# how to deal with genes for which several values are present in the expression file, in case these values have conflicting information
# possible methods: "remove", "min", "max", "mean", "median"

gpr_qualitative: true
  # if true, the gene expression will be converted to reaction weights -1/0/1
  # if false, the expression will directly be mapped to the reactions

gpr_high_cutoff: 0.75
  # the percentile cutoff for high gene expression (this is only used if qualitative: true)
  # example: with 0.75, the genes above the 75th percentile are converted to 1

gpr_low_cutoff: 0.25
  # the percentile cutoff for low gene expression (this is only used if qualitative: true)
  # example: with 0.25, the genes below the 25th percentile are converted to -1


### these parameters are for additional constraints on the metabolic model (optional)

force_flux_bounds: testdata/iJO1366_bounds.csv
# manually define the lower and upper flux bounds for some reactions
# this should be a text or csv file where the column headers are: reaction_ID, condition1_lb, condtion1_ub, etc...
# and each line contains the bounds for one reaction in all conditions

force_active_reactions:
# manually define reactions that must carry flux, and their minimum flux value
# particularly useful for reversible reactions that could carry flux in either direction
# this should be a text file where each line is a reaction ID

fluxvalue: 1.0
# 'fluxvalue' is the absolute value that will be used for forcing flux in 'force_active_reactions'
# Defaults to 1.0

### these parameters are for the network computation in the final step

final_network: union
# defines the method used for computing the network at the end of the workflow
# must be 'union' or 'minimal' or 'none'
# 'union' contains all reactions which are active in at least one DEXOM solution
# 'minimal' contains only the reactions which are active in every solution + the reactions necessary to make the network flux-consistent
# 'none' will output the original model with no modifications

union_cutoff: 0
# only for the 'union' method
# for a given reaction, if the number of solutions in which it is active <= union_cutoff, then this reaction is ignored


### these parameters are for the network enumeration

batch_rxn_sols: 20
# number of reaction-enum solutions per batch. If running on a local machine, there is only 1 batch

full_rxn_enum: false
  # if set to true, this parameter forces reaction-enum to be applied on all reactions from the model
  # the number of batch_rxn_sols will then be ignored
  # this will strongly increase computation times for large models, but maximizes the spread of starting points for the diversity-enum batches

batch_div_sols: 10
# number of diversity-enum solutions per batch. If running on a local machine, there is only 1 batch


#### CLUSTER PARAMETERS #####


batch_num: 2
# number of parallel batches for each condition

cores: 12
# number of cores to assign for each job

memory: 48
# allocated memory per job in gigabytes

time: 10:00:00
# maximum allowed runtime per job in hours:minutes:seconds

force_cplex: true
# if True, the optimizations will be run only if the cplex solver is available
# OCMMED has not been tested with other solvers

suppress_slurmfiles: true
# when set to "true", suppresses the slurm output files in the format "slurm-[jobID].out"
# this is useful to avoid cluttering the cluster folder with many redundant output files
# but if an error occurs the error message won't appear in the logs.


#### ADDITIONAL PARAMETERS FOR ADVANCED USERS ####


### This file contains parameters which can be modified if needed
# parameters with the tag OPTIONAL can be left empty if the file is not present

model_params:
  solver: cplex
  # must be a solver supported by cobrapy (currently: either cplex, glpk or gurobi), and must be correctly installed
  # see instructions for cplex installation in the dexom_python documentation
  timelimit: 600
  # solver timelimit for each optimization step (in seconds). Leave empty for no timelimit
  tolerance: 1e-7
  # solver tolerances. Affects the speed of the solver
  mipgaptol: 1e-3
  # solver MIP gap tolerance. Affects the speed of the solver
  verbosity: 1
  # solver verbosity (1 for no solver output, 2 for warnings, 3 for full solver output)

imat_params:
  epsilon: 3e-4
  # minimum flux value for reactions associated with highly expressed genes
  threshold: 2e-4
  # threshold for determining whether a reaction is active or inactive (must be greater than solver tolerance)

enum_params:
  objective_tolerance: 0
  # tolerance for the objective function when searching for equally optimal solutions during the enumeration
  # if you are using discrete weights instead of qualitative weights, increase this parameter up to 1e-2 for faster runtimes

rxn_enum_params:
  reaction_list:
  # OPTIONAL
  # providing a curated list of non-essential, non-blocked reactions in a shuffled order improves the performance of the reaction-enum method
  # if left empty, a shuffled reaction list will be generated automatically, but blocked and essential reactions will not be excluded

div_enum_params:
  dist_anneal: 0.9
  # parameter for controlling the distance between each successive diversity-enum solution
  # This parameter is ignored in the cluster pipeline, as it will be calculated based on the number of batches and iterations
  icut: true
  # if true, will apply integer-cut constraints. This will prevent diversity-enum from finding duplicate solutions
  full: false
  # if true, will use the full-DEXOM implementation (see dexom-python documentation).
  # This very significantly increases the computation time per iteration and should only be done on small models

blocked_rxns:
# OPTIONAL
# provide a list of reactions which are blocked in the model.
# This will be used for determining which reactions are inactive in the cell-specific model