
### these are the filepaths used in the pipeline

modelpath: pilot_data/Human-GEM11.xml
# must be a valid cobrapy model (either .xml, .json, or .mat)
expressionfile: pilot_data/gene_IDs_meanvalues.csv
# must be a csv file with gene identifiers in one column and gene expression data in other columns
output_path: pilot_data_results
# path to a folder in which the output files will be saved. If the folder does not exist, it will be created


### these parameters are for the gene expression file

gene_ID_column: ID
# name of the column containing gene IDs
gene_expression_columns:
# names of the columns containing gene expression data
# column names must be separated by commas (example: condition1,condition2,condition3)
# if empty, all columns (except the gene_ID_column) will be used
duplicates: remove
# how to deal with genes for which several values are present in the expression file, in case these values have conflicting information
# possible methods: "remove", "min", "max", "mean", "median"
gpr_parameters:
  # parameters for the gene-protein-reaction rules
  qualitative: true
  # if true, the gene expression will be converted to reaction weights -1/0/1
  # if false, the expression will directly be mapped to the reactions
  percentile: 0.25
  # the percentile cutoff for low/high gene expression (this is only used if qualitative: true)
  # example: with 0.25, the genes with the lowest 25% expression are converted to -1, and the highest 25% expression to 1

reaction_scores: false
# set this to true if the "gene expression file" already contains reaction identifiers instead of gene identifiers.
# If true, the conversion of gene expression to reaction weights will be skipped, and the provided scores will be mapped directly on the reactions.


### these parameters are for the network enumeration

force_active_reactions: true
# define whether some reactions in the model should be forced to carry flux
active_reactions: # use the reaction IDs from the model to define the reactions which must carry flux
#  - MAR13082 # this is the generic biomass reaction for human1
  - MAR09931 # this is the biomass maintenance reaction with upper bound 0
fluxvalue: 1e-4
# minimum value that the flux should have.

force_flux_bounds:
#  MAR03905: 0,1000
# manually define the lower and upper flux bounds for some reactions

rxn_enum_iterations: 3
div_enum_iterations: 3
# number of iterations for reaction-enum and diversity-enum (if using the main.py script)


### these parameters are for the network computation in the final step

final_network: union
# defines the method used for computing the network at the end of the workflow
# must be either 'union' or 'minimal'
# 'union' contains all reactions which are active in at least one DEXOM solution
# 'minimal' contains only the reactions which are active in every solution + the reactions necessary to make the network flux-consistent